<a href="https://colab.research.google.com/github/Sreenivas77-star/Python/blob/main/Pandas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import pandas as pd

In [28]:
num_samples = 20

age = np.random.randint(18, 65, num_samples)
salaries = np.random.randint(20000, 100000, num_samples)
gender = np.random.choice(['Male', 'Female'], num_samples)
employee_id = np.random.randint(10000000,200000000, num_samples)
dept = np.random.choice(['HR', 'IT', 'Finance', 'Marketing'], num_samples)

In [33]:
data_dict = {
  "Age" : age,
  "Salary" : salaries,
  "Gender": gender,
  "EmployeeID": employee_id,
  "Dept": dept
}

In [36]:
data = pd.DataFrame(data_dict)
data

    Age  Salary  Gender  EmployeeID       Dept
0    64   37214  Female    78344020  Marketing
1    47   64821  Female    30259665         HR
2    44   97222    Male   149430360  Marketing
3    24   36610    Male   169152298         HR
4    45   97747  Female    86666357    Finance
5    20   83630  Female   153694674  Marketing
6    43   78382  Female    65465801    Finance
7    42   92132  Female    94035439  Marketing
8    64   39296    Male   153516441         HR
9    29   53824    Male   191866626         HR
10   32   94726    Male   121464111  Marketing
11   31   37008    Male    72410514    Finance
12   24   85244  Female    62905120         IT
13   60   20146  Female    79617844    Finance
14   35   38693  Female   176597106    Finance
15   36   93147    Male   132605887    Finance
16   22   68087    Male   199578365         IT
17   32   61170  Female    72789795    Finance
18   18   75550  Female   104022971         HR
19   36   65566    Male    40830274  Marketing

In [56]:
data.isnull()

      Age  Salary  Gender  EmployeeID   Dept
0   False   False   False       False  False
1   False   False   False       False  False
2   False   False   False       False  False
3   False   False   False       False  False
4   False   False   False       False  False
5   False   False   False       False  False
6   False   False   False       False  False
7   False   False   False       False  False
8   False   False   False       False  False
9   False   False   False       False  False
10  False   False   False       False  False
11  False   False   False       False  False
12  False   False   False       False  False
13  False   False   False       False  False
14  False   False   False       False  False
15  False   False   False       False  False
16  False   False   False       False  False
17  False   False   False       False  False
18  False   False   False       False  False
19  False   False   False       False  False

In [58]:
data.dropna(inplace = True)
data

    Age  Salary  Gender  EmployeeID       Dept
0    64   37214  Female    78344020  Marketing
1    47   64821  Female    30259665         HR
2    44   97222    Male   149430360  Marketing
3    24   36610    Male   169152298         HR
4    45   97747  Female    86666357    Finance
5    20   83630  Female   153694674  Marketing
6    43   78382  Female    65465801    Finance
7    42   92132  Female    94035439  Marketing
8    64   39296    Male   153516441         HR
9    29   53824    Male   191866626         HR
10   32   94726    Male   121464111  Marketing
11   31   37008    Male    72410514    Finance
12   24   85244  Female    62905120         IT
13   60   20146  Female    79617844    Finance
14   35   38693  Female   176597106    Finance
15   36   93147    Male   132605887    Finance
16   22   68087    Male   199578365         IT
17   32   61170  Female    72789795    Finance
18   18   75550  Female   104022971         HR
19   36   65566    Male    40830274  Marketing

In [50]:
data[['Age','Gender']]

    Age  Gender
0    64  Female
1    47  Female
2    44    Male
3    24    Male
4    45  Female
5    20  Female
6    43  Female
7    42  Female
8    64    Male
9    29    Male
10   32    Male
11   31    Male
12   24  Female
13   60  Female
14   35  Female
15   36    Male
16   22    Male
17   32  Female
18   18  Female
19   36    Male

In [52]:
data.describe()

             Age      Salary    EmployeeID
count  20.000000     20.0000  2.000000e+01
mean   37.400000  66010.7500  1.117627e+08
std    13.816085  24521.9525  5.104207e+07
min    18.000000  20146.0000  3.025966e+07
25%    27.750000  39145.2500  7.269497e+07
50%    35.500000  66826.5000  9.902920e+07
75%    44.250000  86966.0000  1.535610e+08
max    64.000000  97747.0000  1.995784e+08

In [47]:
print(data.shape)

(20, 5)

In [48]:
data['Age']

0     64
1     47
2     44
3     24
4     45
5     20
6     43
7     42
8     64
9     29
10    32
11    31
12    24
13    60
14    35
15    36
16    22
17    32
18    18
19    36
Name: Age, dtype: int64

In [45]:
print(data)

    Age  Salary  Gender  EmployeeID       Dept
0    64   37214  Female    78344020  Marketing
1    47   64821  Female    30259665         HR
2    44   97222    Male   149430360  Marketing
3    24   36610    Male   169152298         HR
4    45   97747  Female    86666357    Finance
5    20   83630  Female   153694674  Marketing
6    43   78382  Female    65465801    Finance
7    42   92132  Female    94035439  Marketing
8    64   39296    Male   153516441         HR
9    29   53824    Male   191866626         HR
10   32   94726    Male   121464111  Marketing
11   31   37008    Male    72410514    Finance
12   24   85244  Female    62905120         IT
13   60   20146  Female    79617844    Finance
14   35   38693  Female   176597106    Finance
15   36   93147    Male   132605887    Finance
16   22   68087    Male   199578365         IT
17   32   61170  Female    72789795    Finance
18   18   75550  Female   104022971         HR
19   36   65566    Male    40830274  Marketing

In [55]:
data['Age']

0     64
1     47
2     44
3     24
4     45
5     20
6     43
7     42
8     64
9     29
10    32
11    31
12    24
13    60
14    35
15    36
16    22
17    32
18    18
19    36
Name: Age, dtype: int64

In [39]:
data.index

RangeIndex(start=0, stop=20, step=1)

In [35]:
data.values

array([[64, 37214, 'Female', 78344020, 'Marketing'],
       [47, 64821, 'Female', 30259665, 'HR'],
       [44, 97222, 'Male', 149430360, 'Marketing'],
       [24, 36610, 'Male', 169152298, 'HR'],
       [45, 97747, 'Female', 86666357, 'Finance'],
       [20, 83630, 'Female', 153694674, 'Marketing'],
       [43, 78382, 'Female', 65465801, 'Finance'],
       [42, 92132, 'Female', 94035439, 'Marketing'],
       [64, 39296, 'Male', 153516441, 'HR'],
       [29, 53824, 'Male', 191866626, 'HR'],
       [32, 94726, 'Male', 121464111, 'Marketing'],
       [31, 37008, 'Male', 72410514, 'Finance'],
       [24, 85244, 'Female', 62905120, 'IT'],
       [60, 20146, 'Female', 79617844, 'Finance'],
       [35, 38693, 'Female', 176597106, 'Finance'],
       [36, 93147, 'Male', 132605887, 'Finance'],
       [22, 68087, 'Male', 199578365, 'IT'],
       [32, 61170, 'Female', 72789795, 'Finance'],
       [18, 75550, 'Female', 104022971, 'HR'],
       [36, 65566, 'Male', 40830274, 'Marketing']], dtype=object)